### ISSUE TITLE
As a user, I will see a common header and footer across the Breadcrumbs site

### ISSUE THREAD

**Issue by naklers** [nuvention-web/breadcrumbs#9]
- [x] Header and footer elements will be common to all pages in the site, regardless of the auth state of the user
- [x] Header will include
  - [x] Static part: common to and identically placed for authenticated and non-authenticated users
    - [x] The "Breadcrumbs" logo, linking to the top-level URL (see UI flow to see how authenticated users would go to their dashboard, while non-authenticated would go to the HOME)
  - [ ] Dynamic part: changes with authentication status and its elements may be as integrated with or as detached from the static part as need be
    - [ ] If the user is NOT AUTHENTICATED
      - [x] Links to content sections on the HOMEPAGE (#32), per attached mockup/design
      - [x] Link to LOGIN, which opens a dynamically-rendered mini-version of the main login page (PM: I updated this to reflect the current implementation, although the original requirement was to link to a standalone login page)(issue #34)
      - [ ] Link to REGISTER (issue #35) - opens the standalone registration page  
      - [x] Button to DOWNLOAD (issue #32)  
    - [x] If the user is AUTHENTICATED
      - [ ] "Hello" + User's ID (email address?) - e.g. "Hello naklers@yahoo.com"
      - [ ] Link to sign out
- [x] Footer will include
  - [ ] A link to the HOMEPAGE (#32)
  - [ ] A link to the terms of use (#32)
  - [ ] A link to a privacy info page (#32)
  - [ ] A link to learn more about Breadcrumbs, going to the HOMEPAGE (#32)
  - [ ] A link to the DOWNLOAD section of the HOMEPAGE (#32)
  - [ ] A link to "How it works" section on the HOMEPAGE (#32)
  - [ ] Link to Breadcrumbs' Twitter account
  - [ ] Link to send a mail to the Breadcrumbs team
